# Each career has roles defined in
# https://github.com/niteoweb/handbook/blob/master/5_People/salary-system.md#roles
#
# For each role, we get the median US salary from Salary.com, which
# is annual amount in USD, we divide it by 12 and further divide it
# by the 10-year average of EUR -> USD exchange rate from ofx.com.
# We get a monthly base salary in EUR.
eur_to_usd_10_year_avg: 1.20
careers:

-   name: Design
    roles:
    -   name: Junior Designer
        baseSalary: 4464
        salary_com_key: web-designer-i

    -   name: Designer
        baseSalary: 4956
        salary_com_key: web-designer-ii

    -   name: Senior Designer
        baseSalary: 6070
        salary_com_key: web-designer-iii

    -   name: Lead Designer
        baseSalary: 7412
        salary_com_key: web-designer-iv

    -   name: Principal Designer
        baseSalary: 8139
        salary_com_key: web-art-director


-   name: Marketing
    roles:
    -   name: Junior Digital Marketer
        baseSalary: 3915
        salary_com_key: digital-marketing-analyst-i

    -   name: Digital Marketer
        baseSalary: 4797
        salary_com_key: digital-marketing-analyst-ii

    -   name: Senior Digital Marketer
        baseSalary: 6373
        salary_com_key: digital-marketing-analyst-iii

    -   name: Lead Digital Marketer
        baseSalary: 7035
        salary_com_key: digital-marketing-manager

    -   name: Principal Digital Marketer
        baseSalary: 11188
        salary_com_key: digital-marketing-director


-   name: Operations
    roles:
    -   name: Tech Support I
        baseSalary: 4217
        salary_com_key: technical-support-analyst-i

    -   name: Tech Support II
        baseSalary: 5291
        salary_com_key: technical-support-analyst-ii

    -   name: Support Manager
        baseSalary: 5840
        salary_com_key: it-project-manager-i

    -   name: Project Manager
        baseSalary: 7316
        salary_com_key: it-project-manager-ii

    -   name: Operations Manager
        baseSalary: 8796
        salary_com_key: it-project-manager-iii


-   name: Technical
    roles:
    -   name: Junior Software Engineer
        baseSalary: 4757
        salary_com_key: software-engineer-i

    -   name: Software Engineer
        baseSalary: 6105
        salary_com_key: software-engineer-ii

    -   name: Senior Software Engineer
        baseSalary: 7574
        salary_com_key: software-engineer-iii

    -   name: Lead Software Engineer
        baseSalary: 9116
        salary_com_key: software-engineer-iv

    -   name: Principal Software Engineer
        baseSalary: 10350
        salary_com_key: software-engineer-v

    -   name: Information Technology Director
        baseSalary: 12087
        salary_com_key: information-technology-director


# For each country we get the ratio between US and that country's Numbeo
# Cost of Living Plus Rent Index value. Example: if Country A
# is 30% cheaper based on Cost of Living Plus Rent Index, then
# this country's `cost_of_living` is 0.7.
#
# Then, we want to slightly underpay people in expensive
# locations and not-so-slightly overpay people in cheap locations:
#  - in cheap locations, a MacBook costs the same (if not more);
#  - people in cheap locations can easily work remotely for a
#    company in a more expensive location;
#  - by overpaying cheap locations, we get access to top talent there;
#  - by underpaying expensive locations our hiring is harder there so
#    the culture fit must be greater.
#
# Additionally, we cannot afford to pay US-level salaries, so we
# set set our "affordability" ratio here, that we use to decrease
# `cost_of_living` values, which effectively decreases our salaries.
# The value is set somewhat arbitrarily, to match our salaries before
# the introduction of the Salary Calculator in Niteo. We adjust the
# "affordability" ratio in January, based on the previous year's
# performance.
#
# Finally for each country, we "compress" the `cost_of_living` towards
# our `affordability`. This means that if `cost_of_living` is higher
# than `affordability`, we decrease `cost_of_living` by 2/3 of the
# difference. If `cost_of_living` is lower than `affordability`, we
# increase `cost_of_living` by 2/3 of the difference.
#
# See `countries` and `compress_towards_affordability` functions in
# https://github.com/niteoweb/salarycalc/blob/master/fetch_config_values.py
# for exact details on these calculations.
affordability: 0.49
countries:

-   name: Germany
    cost_of_living: 0.83
    compressed_cost_of_living: 0.6

-   name: Guatemala
    cost_of_living: 0.54
    compressed_cost_of_living: 0.51

-   name: India
    cost_of_living: 0.28
    compressed_cost_of_living: 0.42

-   name: Japan
    cost_of_living: 0.99
    compressed_cost_of_living: 0.65

-   name: Netherlands
    cost_of_living: 0.98
    compressed_cost_of_living: 0.65

-   name: Philippines
    cost_of_living: 0.42
    compressed_cost_of_living: 0.47

-   name: Portugal
    cost_of_living: 0.64
    compressed_cost_of_living: 0.54

-   name: Romania
    cost_of_living: 0.41
    compressed_cost_of_living: 0.46

-   name: Serbia
    cost_of_living: 0.41
    compressed_cost_of_living: 0.46

-   name: Slovenia
    cost_of_living: 0.64
    compressed_cost_of_living: 0.54

-   name: Spain
    cost_of_living: 0.68
    compressed_cost_of_living: 0.55

-   name: Uganda
    cost_of_living: 0.36
    compressed_cost_of_living: 0.45

-   name: Ukraine
    cost_of_living: 0.39
    compressed_cost_of_living: 0.46

-   name: United Kingdom
    cost_of_living: 0.88
    compressed_cost_of_living: 0.62

-   name: United States
    cost_of_living: 1.0
    compressed_cost_of_living: 0.66
