# When we calculate Niteo's base salary in EUR we take the
# 10-year average of EUR -> USD exchange rate.
eur_to_usd_10_year_avg: 1.1988

# We cannot afford to pay San Francisco-level salaries, so
# set set our "affordability" ratio here -- all base salaries
# are calculated based on SF salary * affordability_ratio
# We took 0.53 because it is the averaged out salary between
# Amsterdam, Berlin, Barcelona and Lisbon; compared to SF.
affordability_ratio: 0.53

countries:

-   name: Netherlands
    locationFactor: 0.98

-   name: Spain
    locationFactor: 0.68

-   name: Germany
    locationFactor: 0.84

-   name: Romania
    locationFactor: 0.41

-   name: Philippines
    locationFactor: 0.42

-   name: India
    locationFactor: 0.27

-   name: Ukraine
    locationFactor: 0.4

-   name: Portugal
    locationFactor: 0.64

-   name: Slovenia
    locationFactor: 0.64

-   name: United Kingdom
    locationFactor: 0.88

-   name: Serbia
    locationFactor: 0.41

-   name: India
    locationFactor: 0.27

-   name: United States
    locationFactor: 1.0

-   name: Japan
    locationFactor: 1.0

careers:

-   name: Design
    roles:
    -   name: Junior Designer
        baseSalary: 2923

    -   name: Designer
        baseSalary: 2926

    -   name: Senior Designer
        baseSalary: 2923

    -   name: Lead Designer
        baseSalary: 2923

    -   name: Principal Designer
        baseSalary: 5215


-   name: Marketing
    roles:
    -   name: Marketing Associate
        baseSalary: 2181

    -   name: Digital Marketing Specialist
        baseSalary: 2919

    -   name: Senior Digital Marketing Specialist
        baseSalary: 2949

    -   name: Product Marketing Manager
        baseSalary: 4807

    -   name: Senior Product Marketing Manager
        baseSalary: 4807


-   name: Operations
    roles:
    -   name: Customer Support Specialist
        baseSalary: 1322

    -   name: Customer Support Associate
        baseSalary: 1356

    -   name: Technical Support Specialist
        baseSalary: 1798

    -   name: Operations Manager
        baseSalary: 4012

    -   name: Senior Operations Manager
        baseSalary: 4012


-   name: Technical
    roles:
    -   name: Junior Programmer
        baseSalary: 2615

    -   name: Junior Software Engineer
        baseSalary: 4926

    -   name: Software Engineer
        baseSalary: 4922

    -   name: Lead Software Engineer
        baseSalary: 4926

    -   name: Principal Software Engineer
        baseSalary: 6243

