version: 2

defaults: &defaults
    working_directory: ~/repo
    docker:
      - image: circleci/node:9.4.0

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only: master


jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "package.json" }}
            - v4-dependencies-

      - run:
          name: Updating npm
          command: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then sudo npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi

      - run:
          name: Installing dependencies
          command: make .installed

      - run:
          name: Running linters
          command: make lint

      - run:
          name: Running tests
          command: make tests

      - run:
          name: Generating coverage report
          command: make codecov

      - run:
          name: Compiling salary-calculator.js
          command: make dist

      - save_cache:
          key: v4-dependencies-{{ checksum "package.json" }}
          paths:
            - /home/circleci/.npm
            - /home/circleci/.elm
            - elm-stuff
            - tests/elm-stuff

      - persist_to_workspace:
          root: ~/repo
          paths: .

  publish:
    <<: *defaults

    steps:
      - attach_workspace:
            at: ~/repo

      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc

      - run:
          name: Updating npm
          command: npmv=$(echo $(npm -v) | head -c 1); if [ "$npmv" -lt "6" ]; then sudo npm i -g npm; else echo "Node.js Docker Team finally decided to include npm v6+ in latest image; you can remove this script now"; fi

      - run:
          name: Clean the dependencies cache
          command: make clean
          # See https://github.com/niteoweb/salarycalc/issues/14

      - run:
          name: Publish the package to NPM
          command: make publish
